# Generated by Django 3.2.9 on 2021-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtests',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
