# Generated by Django 3.2.9 on 2021-11-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_labtests_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtests',
            options={'ordering': ['name']},
        ),
    ]
