# Generated by Django 3.2.9 on 2021-11-15 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients_name', models.CharField(max_length=200)),
                ('patients_age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150, 'Age cannot be greater than 150')])),
                ('patients_contact', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=150)),
                ('tests_to_carry', models.TextField(max_length=500)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
