# Generated by Django 3.2.9 on 2021-11-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20211118_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tests_to_carry',
            field=models.CharField(choices=[('haemoglobin', 'haemoglobin'), ('malaria', 'malaria'), ('cholera', 'cholera'), ('ebola', 'ebola'), ('fever', 'fever'), ('timezone', 'timezone'), ('django', 'django'), ('modules', 'modules'), ('customuser', 'customuser'), ('patients', 'patients'), ('bootstrap', 'bootstrap'), ('react', 'react'), ('mams', 'mams'), ('nauend', 'nauend'), ('maidm', 'maidm'), ('cndsi', 'cndsi'), ('adqw', 'adqw'), ('qwwq', 'qwwq')], max_length=500),
        ),
    ]
