# Generated by Django 3.2.9 on 2021-11-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('patients', '0004_alter_patient_tests_to_carry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='tests_to_carry',
        ),
        migrations.AddField(
            model_name='patient',
            name='tests_to_carry',
            field=models.ManyToManyField(to='services.LabTests'),
        ),
    ]
