# Generated by Django 3.2.9 on 2021-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20211118_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patients_sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=6),
            preserve_default=False,
        ),
    ]
