# Generated by Django 3.2.9 on 2021-11-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_patients_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
